name: JupyterLab Docker Image - Build and Publish
on:
  push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  base:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    - name: Login to docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
    - name: Build
      run: docker build -t nycplanning/open_data_ingest:latest -f jupyterlab/Dockerfile .
    - name: Publish
      run: docker push nycplanning/open_data_ingest:latest
